# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generateUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_generatePass(object):
    def setupUi(self, generatePass):
        generatePass.setObjectName("generatePass")
        generatePass.resize(233, 109)
        self.label = QtWidgets.QLabel(generatePass)
        self.label.setGeometry(QtCore.QRect(10, 10, 171, 41))
        self.label.setObjectName("label")
        self.lengthPass = QtWidgets.QLineEdit(generatePass)
        self.lengthPass.setGeometry(QtCore.QRect(180, 20, 41, 21))
        self.lengthPass.setObjectName("lengthPass")
        self.copyButton = QtWidgets.QPushButton(generatePass)
        self.copyButton.setGeometry(QtCore.QRect(60, 60, 111, 24))
        self.copyButton.setObjectName("copyButton")

        self.retranslateUi(generatePass)
        QtCore.QMetaObject.connectSlotsByName(generatePass)

    def retranslateUi(self, generatePass):
        _translate = QtCore.QCoreApplication.translate
        generatePass.setWindowTitle(_translate("generatePass", "Dialog"))
        self.label.setText(_translate("generatePass", "Enter the length of password :"))
        self.copyButton.setText(_translate("generatePass", "Copy to clipboard"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    generatePass = QtWidgets.QDialog()
    ui = Ui_generatePass()
    ui.setupUi(generatePass)
    generatePass.show()
    sys.exit(app.exec_())
